### ISSUE TITLE
Update the message prior to start the session.

### ISSUE THREAD

**Issue by Penn-EDS** [Penn-EDS/Two-Channel-Drug-Delivery-controller-mice#2]
This text warns the last chance prior to execute the parameters. 

Last chance!
Are mice in the box?

**Comment by Penn-EDS** [comment]
Text goes up for being exactly 20 characters in the Are mice in the box? 
Change it to Are mice in box?

**Comment by mizakata** [comment]
Issue resolved

**Comment by Penn-EDS** [comment]
Closed
