### ISSUE TITLE
Bugs related to setup and code cleanup. 

### ISSUE THREAD

**Issue by Penn-EDS** [Penn-EDS/Two-Channel-Drug-Delivery-controller-mice#3]
•	The maximum number of reinforcers/puffs should apply only to the active wheel.
o	Right now the maximum number of puffs = inactive + active. 
•	Fixed ratio is not correct when >1
o	This one took forever to double check. For example, right now when the FR is set to 6 it only takes 5 wheel spins to get a puff. At first I thought it was only a file writing issue but it is definitely a wheel spinning issue. FR1 seems to work fine, but at FR2 it only requires 1, FR3 requires 2 etc. **< This is a separate issue in Git>**
	Geometric ratio works great.
•	Priming puff does not work
o	This was a problem with an earlier iteration of the program that I think had been fixed, but it is not working now so hopefully it will be easy to put right.
	The system does not deliver a puff, but it does write to the SD card that it did.
•	Can we reduce the delay in the "Session Ended/Cancelled" and "Cleaning Cancelled" screens? Maybe to one second? 
o	Usually it doesn't matter but a couple of times I've had to quickly stop, fix something, and restart and those extra seconds feel like an eternity!
Alex already suggested a good fix for my other problem, which is that I promptly lost an SD card in the chassis. (Thanks Alex!)

**Comment by asantoslozada** [comment]
All this points are done. The second point will be discussed with Jessica to see how she will like to print the puff in the fixed ratio.
