### ISSUE TITLE
Jessica's issue about the FR>1

### ISSUE THREAD

**Issue by Penn-EDS** [Penn-EDS/Two-Channel-Drug-Delivery-controller-mice#4]
This one took forever to double check. For example, right now when the FR is set to 6 it only takes 5 wheel spins to get a puff. At first I thought it was only a file writing issue but it is definitely a wheel spinning issue. FR1 seems to work fine, but at FR2 it only requires 1, FR3 requires 2 etc.

**Comment by asantoslozada** [comment]
Solved
