### ISSUE TITLE
Change wheel turn requirement

### ISSUE THREAD

**Issue by ShawJK** [Penn-EDS/Two-Channel-Drug-Delivery-controller-mice#6]
Can we change the wheel turn requirement to be considered a response to a quarter turn? I think this is changing line 162 in Main.ino from "int Step = 8" to "int Step = 2".

Hopefully I've done this right!

**Comment by asantoslozada** [comment]
Step variable changed to two and priming puff has a post-response time out execution.

**Comment by ShawJK** [comment]
Seems to work great; wheel triggers puff on the quarter turn. Alex also updated the code to include a post-prime timeout (thank you!) which also appeared to work correctly when tested.
